### ISSUE TITLE
(0xc00007b)  Error 

### ISSUE THREAD

**Issue by egycnq** [PS3Xploit/PS3xploit-resigner#1]
![45646](https://user-images.githubusercontent.com/36681650/36952365-97475a64-2017-11e8-92d3-81b72841942f.png)

Can't run the program because of this error.

Installed all cygwin DLL files. 

Visual c++ Runtime installed. 

I have Windows 10 pro 64bit .

**Comment by PS3Xploit** [comment]
Hi
You need 64 bit dlls in the same directory as the tool. Or you can compile with cl for x64 with minor changes to the code

**Comment by egycnq** [comment]
thx its work for me now 👍
