### ISSUE TITLE
OMG 

### ISSUE THREAD

**Issue by goodandrewsoft** [PS3Xploit/PS3xploit-resigner#11]
Wher get idps.hex and act file ? 
Anybody help i'm find in all internet and nothing !!

**Comment by Caio99BR** [comment]
Look here: http://www.psx-place.com/threads/tutorial-the-great-ps3xploit-3-0-han-all-in-one-guide.16979/

Close this Issue, because it isn't a Issue.

**Comment by andoryuu3** [comment]
> Wher get idps.hex and act file ?
> Anybody help i'm find in all internet and nothing !!

It pains me to know that we share the same name. Please change yours, or please learn to read for more than 15 seconds at a time. You might actually learn something, including the answer to your question.

(HINT: You can also find the answer to your question SOMEWHERE on ps3xploit.com ...Good luck!) 

I also agree that you should close this issue. Use web forums and reddit to post silly questions if you must. Just don't bring it to GitHub.

**Comment by PS3Xploit** [comment]
This is not an issue!

**Comment by goodandrewsoft** [comment]
Really? OMG. Sorryyyy!!!! 
How I can live after this , cry!

**Comment by Caio99BR** [comment]
Man, you dont need to post anything, just research and use, I already posted you a good link.

If not, sorry...
