### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Oneshinw3** [PS3Xploit/PS3xploit-resigner#16]
When I put a .pkg file in the /imput/pkgs and run the resign_windows.bat . It doesn't output a signed .pkg . Nothing is there when the thing is done..

**Comment by ShaolinAssassin** [comment]
Weird. It's working for me.

**Comment by tomazzz369** [comment]
tested two packages on PS3xploit Resigner 2.1.0 and i have no issues

**Comment by Oneshinw3** [comment]
I found my problem. It was my anti-virus. Even if it wasn't running it was still removing a file that wasn't making the cmd prompt working.
