### ISSUE TITLE
Threat Detection

### ISSUE THREAD

**Issue by Henshin87** [PS3Xploit/PS3xploit-resigner#17]
Every time i download the zip windows defender detects it as a trojan and it wont let me download the files. Is the file ok to run i just want to make sure.

**Comment by PS3Xploit** [comment]
There is no threat, src is freely available. But yeah windows defender does say it has some virus but it’s false alarm.

**Comment by socram8888** [comment]
Not just Windows - 23 out of 61 antivirus in VirusTotal agree it's packed with a trojan.

Source code is indeed clean but given it's not using deterministic build, there's no way to be sure these exes do actually correspond to the provided source and have not been infected.
