### ISSUE TITLE
Running on macOS - corrupted RIF PKG?

### ISSUE THREAD

**Issue by khwalkowicz** [PS3Xploit/PS3xploit-resigner#19]
I tried building & running the package under macOS 10.12 Sierra.

In order to make it work I had to:
 - in the Makefile, set the CFLAGS and LDFLAGS TO:
```bash
CFLAGS=-pipe -fvisibility=hidden -D_GNU_SOURCE -O3 -D_FILE_OFFSET_BITS=64 -I/usr/local/opt/openssl/include
LDFLAGS=-lcrypto -lssl -L/usr/local/opt/openssl/lib
```
- in the Shell script, change all uses of readlink to greadlink (if neccesarry, install *coreutils* with homebrew) 
- in the Shell script, remove the test for *python-dev* headers (on mac when installing python with homebrew the headers are there by default and there is no separate package for them)

While everything seems to be working, the outputted RIF PKG is probably corrupted - every attempt to install it ends up with an error (80029567 or 80029564 - depends on whether running with debugging on or off).

Any ideas on how to get it working under mac?

**Comment by khwalkowicz** [comment]
If you don't have a mac to test on I'm okay to help testing any ideas, just need to know what exactly to do, since the script itself doesnt produce any errors while running

**Comment by PS3Xploit** [comment]
80029567 is error with signing.
Maybe get the log and post here

Test environment should be with han enabled and nothing else

And yeah I don’t have a Mac to test unfortunately but if you get it working I’ll happily push that in next commit

**Comment by khwalkowicz** [comment]
I found the possible source of the problem:

${PS3XPLOIT_RESIGNER_BINARY} "${rif_pkg_name}" <<< echo -e '\n\n';

gives 

4787 Segmentation fault: 11

**Comment by R4ndom** [comment]
@khwalkowicz I figured it out. I got the same error "Segmention fault: 11", I spent couple of hours to fix it. My OS: macOS 10.13.5. In file **[pkg.py](https://github.com/PS3Xploit/PS3xploit-resigner/blob/master/source/tools/ps3py/pkg.py)** you need to comment [535 line](https://github.com/PS3Xploit/PS3xploit-resigner/blob/master/source/tools/ps3py/pkg.py#L535) to use "slow" implementation, and it worked for me - hope for you too

**Comment by sittingcow** [comment]
Thank you so much, nixu1337!!! (I'm just using Windows 10 in VirtualBox on macOS 10.10.5, but had the same RIF PKG corruption issue)

**Comment by esc0rtd3w** [comment]
added fixes. please test if you can

**Comment by PS3Xploit** [comment]
thanks for the input, any additional feedback would be helpful, if problems still exist
