### ISSUE TITLE
Error on game with 45 gb size

### ISSUE THREAD

**Issue by zeroxragde** [PS3Xploit/PS3xploit-resigner#20]
![error](https://user-images.githubusercontent.com/4545852/41443960-e3523014-700d-11e8-8b40-f6cbc8ba517f.png)

**Comment by PS3Xploit** [comment]
First thing first, I assume you are running the latest version?

How did you even get 45gb pkg. if it’s blu ray convert, simply use debug pkg enabler and install the pkg.

Do you have enough free space on HDD?

If all of this is fine then it’s the pkg that is corrupted most likely.

**Comment by ElvisTekencio** [comment]
Hi, i had the same problem, but the game was Dragon's Dogma Dark Arisen, a reddit user told me just to install the .pkg without resigning it, and install the .rif, and the game worked. Try it and tell us. Good Luck.

**Comment by cygmon0** [comment]
I had it before, then, i realized it was there is no enough space on my HDD. cleaned the disk and resigned the pkg successfully
