### ISSUE TITLE
Compile in archlinux

### ISSUE THREAD

**Issue by letroll** [PS3Xploit/PS3xploit-resigner#21]
When I am trying to compile it by using "make" it fails with:

[C] pkg2zip_aes_x86.c
/bin/ld : ne peut trouver -lcrypto
/bin/ld : ne peut trouver -lssl
collect2: error: ld a retourné le statut de sortie 1
Failed to link ps3xploit_rifgen_edatresign!
make: *** [Makefile:11: ps3xploit_rifgen_edatresign] Error 1

someone can help me or share me it's pre-compiled binary?

**Comment by Ankush-p** [comment]
Pre-compiled binary (I compiled in Arch too)
[ps3xploit_rifgen_edatresign.zip](https://github.com/PS3Xploit/PS3xploit-resigner/files/2152243/ps3xploit_rifgen_edatresign.zip)
Place it in `source/pre-compiled/linux`

**Comment by PS3Xploit** [comment]
sudo apt-get install libssl-dev
