### ISSUE TITLE
Where can I Find Act.dat and idps.hex please help

### ISSUE THREAD

**Issue by Official-Ahmed** [PS3Xploit/PS3xploit-resigner#23]
I have an issue when i try to resign my pkg game it resigns fine but when I try to resign the rap nothing happens only the words " verify your files" but I think the problem is because of these files Act.dat and idps.hex now I just wanna know do I get these from ?

**Comment by tomazzz369** [comment]
> "Where can I Find Act.dat and idps.hex please help"

check under your bed... if still nothing, check on http://www.ps3xploit.com/help/han.html

**Comment by Dr-Vee** [comment]
This issue should be closed.

**Comment by SmaxchTrax** [comment]
a mi igual me pasa lo mismo y si tengo los 2 archivos

**Comment by Official-Ahmed** [comment]
So funny shall we laugh I got it since 1990, thanks bro

On 06:03, Mon, Aug 27, 2018 tomazzz369 <notifications@github.com> wrote:
>>
>> "Where can I Find Act.dat and idps.hex please help"
>
> check under your bed... if still nothing, check on
http://www.ps3xploit.com/help/han.html
