### ISSUE TITLE
Compile in linux

### ISSUE THREAD

**Issue by erickDarko** [PS3Xploit/PS3xploit-resigner#30]
main.cpp: In function ‘long long int current_timestamp()’:
main.cpp:685:27: error: ‘gettimeofday’ was not declared in this scope
Failed to compile main.cpp!

**Comment by PT-nt107** [comment]
add header file
`#include <sys/time.h>`
 in main.cpp

**Comment by TheIgnacio** [comment]
I have a somewhat similar problem gives me this error.
https://mobile.twitter.com/ignacio99595752/status/1111406426298048512
when doing the make and starting the .sh

**Comment by PT-nt107** [comment]
I think u just not install some lib files which include openssl header files,and you can install the libssl-dev package to deal it.

**Comment by TheIgnacio** [comment]
Error main.cpp:1044:25

**Comment by erickDarko** [comment]
installing python-dev, libssl-dev and commenting the line `686 //  gettimeofday(&te, NULL);` work for me

**Comment by PT-nt107** [comment]
The problem I meet in compile in Linux is that I'm using arm64 arch CPU which not support AES-NI SSSE3(two kinds of instructions  on Intel x86 CPU). But when GCC compile pkg2zip_aes_x86.c ,it will use -maes -mssse3 (the gcc on arm64 not support) .

**Comment by TheIgnacio** [comment]
In what file do I have to comment on that line? Now that error is on me.

**Comment by erickDarko** [comment]
main.cpp

**Comment by TheIgnacio** [comment]
Thanks for your help, they helped me a lot since I just could not run it in w xp, Thanks.
