### ISSUE TITLE
resign_linux.sh doesn't work on Arch Linux

### ISSUE THREAD

**Issue by malloc0x3cc** [PS3Xploit/PS3xploit-resigner#37]
In Arch Linux and distributions based on it, the section meant to check for python-dev leads to an error because python-dev is included in the python archlinux package

Fix proposition: [#36](https://github.com/PS3Xploit/PS3xploit-resigner/pull/36)

**Comment by mareasperez** [comment]
> In Arch Linux and distributions based on it, the section meant to check for python-dev leads to an error because python-dev is included in the python archlinux package
> 
> Fix proposition: [#36](https://github.com/PS3Xploit/PS3xploit-resigner/pull/36)

working on Zorin os (Ubuntu Based).
the problem was: 
crypt.c:22:10: fatal error: Python.h: No existe el archivo o el directorio
 #include <Python.h>
          ^~~~~~~~~~


fix is:

sudo apt-get install python-dev
