### ISSUE TITLE
verify your files!﻿

### ISSUE THREAD

**Issue by HeryFlores** [PS3Xploit/PS3xploit-resigner#5]
please help me, when I put the pkg of a game in ps3xploit_rifgen_edatresign the message appears:verify your files!﻿. The file is right, I do not know what else to do.

**Comment by th3d3c1d3r** [comment]
Although I am not the developer but I would imagine you would have to provide a bit more info like:
-file you are trying to resign (name and maybe link)
-does the program behave in the same way for all of your pkg files? Do they otherwise work?
-Are you following the tutorials exactly?

**Comment by HeryFlores** [comment]
yes it behaves like this with all my pkgs, yes it follows the tutorial step by step
this is one of which I tried to install: http: //psndl.net/view-package/2284

**Comment by PS3Xploit** [comment]
Drag and drop the exe and it should work
Make sure your path to exe is not too long

**Comment by RepeatingDigits** [comment]
You need to place the .RAP INSIDE the resigner's folder where the .exe is or else you'll get this error.
Yes it's dumb.

**Comment by HeryFlores** [comment]
I already did it, it does not work

**Comment by dothackjhe** [comment]
@HeryFlores Make sure that the "act.dat" and "idps.hex" files are within the same folder as the "ps3xploit_rifgen_edatresign.exe."

**Comment by dothackjhe** [comment]
@HeryFlores Can you provide a screenshot of your folder? I'm pretty sure that had been quite an obvious deviation with the version 1.30 of the resigner from its former.

**Comment by RepeatingDigits** [comment]
Wait, why are you trying to resign a PKG file? Isn't this program for .rap -> .rif conversion?

**Comment by HeryFlores** [comment]
I tried everything but I could not.
Thank you for trying to help me.

**Comment by dothackjhe** [comment]
Yeah, just like what @RepeatingDigits asked, are you trying to resign a .pkg file instead of its .rap?

**Comment by HeryFlores** [comment]
I'm not trying to .rap

**Comment by HeryFlores** [comment]
- 

- 

- 
![error](https://user-images.githubusercontent.com/37427605/37551768-01bfa988-2986-11e8-94b6-388ff8d38bc2.png)

**Comment by dothackjhe** [comment]
It's the .rap file you should be dragging into "ps3xploit_rifgen_edatresign.exe"

**Comment by HeryFlores** [comment]
Yes I know, but when I play .rap it appears  
![error1](https://user-images.githubusercontent.com/37427605/37551834-470de81e-2987-11e8-969c-67d5b8c6997f.png)

**Comment by RepeatingDigits** [comment]
I know what's wrong. Your act.dat and idps.hex are shortcuts, not the actual files. Those files are actually act.dat.ink and idps.hex.ink.
Copy the files properly with ctrl+c and ctrl+v, (don't just drag them) and try again. And keep in mind, if you're trying to sign a .pkg instead of a .rap, it'll always fail because .pkg files aren't the ones that need signing.

**Comment by dothackjhe** [comment]
@RepeatingDigits  Nice insight.

**Comment by HeryFlores** [comment]
I thought it might be something with these files but when I step from ps3 to the pendrive it comes as a shortcut, will it be my pendrive?

**Comment by dothackjhe** [comment]
I've never had an instance where a file a sent to an external memory storage turned out to be a shortcut. Often, if the file is not cut off, it's just copied.

**Comment by RepeatingDigits** [comment]
If you're just dragging the files, windows might have made a shortcut instead of copying them. Copy them manually.

**Comment by HeryFlores** [comment]
I do not remember if I just dragged or copied and pasted.but it excludes all the files of rage

**Comment by HeryFlores** [comment]
Thank you for helping me. I'll try again tomorrow.

**Comment by Cool123ggcool** [comment]
the way to fix your problem is to select the files then right click then copy then paste to directory then run the program
