### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by chronoss09** [PS3Xploit/PS3xploit-resigner#8]
Where is the 2.0 file ?

**Comment by hexcsl** [comment]
Open your eyes! https://github.com/PS3Xploit/PS3xploit-resigner/tree/master/binary

**Comment by magicseb** [comment]
Can we disable the "press enter" at the end of the process ?

**Comment by PS3Xploit** [comment]
You can disable getchar() to remove the press enter screen
