### ISSUE TITLE
Where is the source code for pkg_exdata.exe , I cant make binary for linux

### ISSUE THREAD

**Issue by assegaf** [PS3Xploit/PS3xploit-resigner#9]
Where is the source code for pkg_exdata.exe , I cant make binary for linux.
Thank you

**Comment by hexcsl** [comment]
Source code pkg_exdata in PS3 Tools Collection (ps3tools\tools\make_pkgs\bin\) - http://www.psx-place.com/resources/ps3-tools-collection.594/
Source code python library (pkgcrypt.pyd) in github - https://github.com/libretro/ps3sx/tree/master/PS3Py

**Comment by assegaf** [comment]
awesome thank you
